name: Release

on:
  push:
    branches: [main]

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@v5.0.0
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: release
    if: ${{ needs.release.outputs.release_created == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: oven-sh/setup-bun@v2.2.0
        with:
          bun-version: 1.4.2
      - uses: actions/setup-node@v7.0.0
        with:
          node-version: 26.10
          registry-url: https://registry.npmjs.org
          package-manager-cache: false
      - run: bun ci
      - run: bun --bun run build
      - run: npm publish --access public --ignore-scripts
